# based on https://github.com/MiyooCFW/gmenunx/blob/master/.github/workflows/c-cpp.yml
name: CI Build

on: [push, pull_request]

jobs:   
  build-modern:
    name: miyooctl for MiyooCFW 1.4+ (musl libc)
    runs-on: ubuntu-20.04
    container:
      image: nfriedly/miyoo-toolchain:latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: miyooctl binary
        path: miyooctl
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
  build-legacy:
    name: miyooctl legacy build for Miyoo <=1.3.3 (uClibc)
    runs-on: ubuntu-20.04
    container:
      image: nfriedly/miyoo-toolchain:steward
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: miyooctl legacy binary
        path: miyooctl
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
